
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

input_select: !include includes/input_selects.yaml
light: !include includes/lights.yaml
#afvalbeheer: !include includes/afvalbeheer.yaml
spotify: !include includes/spotify.yaml

sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp             
    resources:                       
      - restafval
      - gft
      - papier
      - pmd
      - zachteplastic
    postcode: !secret postalcode
    streetname: !secret streetname                
    streetnumber: !secret streetnumber

# Text to speech
tts:
  - platform: google_translate


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
