- platform: afvalbeheer
  wastecollector: RecycleApp             
  resources:                       
    - restafval
    - gft
    - papier
    - pmd
    - zachteplastic
  postcode: !secret postalcode
  streetname: !secret streetname                
  streetnumber: !secret streetnumber
